# Generated by Django 5.2.12 on 2026-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='Unknown', help_text='Enter author name (e.g., Last, First)', max_length=200),
            preserve_default=False,
        ),
    ]
